component: express
name: expressDemo
app: appDemo
inputs:
 entryFile: node.js #以您实际入口文件名为准
 src: ./
 region: ap-shanghai
 runtime: Nodejs10.15
 apigatewayConf:
   protocols:
     - http
     - https
   environment: release